// <auto-generated />
using System;
using DivanSufi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DivanSufi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("DivanSufi.Domain.Entities.CurrentPoemState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<int>("PoemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SharedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SharedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PoemId");

                    b.HasIndex("SharedByUserId");

                    b.ToTable("CurrentPoemStates");
                });

            modelBuilder.Entity("DivanSufi.Domain.Entities.CurrentWaslaState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SharedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SharedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WaslaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SharedByUserId");

                    b.HasIndex("WaslaId");

                    b.ToTable("CurrentWaslaStates");
                });

            modelBuilder.Entity("DivanSufi.Domain.Entities.Maqam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEn")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Maqamat");
                });

            modelBuilder.Entity("DivanSufi.Domain.Entities.Poem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HadraSection")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaqamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PoetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchNormalizedBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchNormalizedPoet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchNormalizedTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MaqamId");

                    b.HasIndex("PoetId");

                    b.ToTable("Poems");
                });

            modelBuilder.Entity("DivanSufi.Domain.Entities.Poet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Poets");
                });

            modelBuilder.Entity("DivanSufi.Domain.Entities.ShareHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShareType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SharedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SharedByUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SharedByUserId");

                    b.ToTable("ShareHistories");
                });

            modelBuilder.Entity("DivanSufi.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DivanSufi.Domain.Entities.Wasla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Waslat");
                });

            modelBuilder.Entity("DivanSufi.Domain.Entities.WaslaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PoemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WaslaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PoemId");

                    b.HasIndex("WaslaId");

                    b.ToTable("WaslaItems");
                });

            modelBuilder.Entity("DivanSufi.Domain.Entities.CurrentPoemState", b =>
                {
                    b.HasOne("DivanSufi.Domain.Entities.Poem", "Poem")
                        .WithMany()
                        .HasForeignKey("PoemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DivanSufi.Domain.Entities.User", "SharedByUser")
                        .WithMany()
                        .HasForeignKey("SharedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poem");

                    b.Navigation("SharedByUser");
                });

            modelBuilder.Entity("DivanSufi.Domain.Entities.CurrentWaslaState", b =>
                {
                    b.HasOne("DivanSufi.Domain.Entities.User", "SharedByUser")
                        .WithMany()
                        .HasForeignKey("SharedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DivanSufi.Domain.Entities.Wasla", "Wasla")
                        .WithMany()
                        .HasForeignKey("WaslaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SharedByUser");

                    b.Navigation("Wasla");
                });

            modelBuilder.Entity("DivanSufi.Domain.Entities.Poem", b =>
                {
                    b.HasOne("DivanSufi.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DivanSufi.Domain.Entities.Maqam", "Maqam")
                        .WithMany("Poems")
                        .HasForeignKey("MaqamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DivanSufi.Domain.Entities.Poet", "Poet")
                        .WithMany("Poems")
                        .HasForeignKey("PoetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Maqam");

                    b.Navigation("Poet");
                });

            modelBuilder.Entity("DivanSufi.Domain.Entities.ShareHistory", b =>
                {
                    b.HasOne("DivanSufi.Domain.Entities.User", "SharedByUser")
                        .WithMany()
                        .HasForeignKey("SharedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SharedByUser");
                });

            modelBuilder.Entity("DivanSufi.Domain.Entities.Wasla", b =>
                {
                    b.HasOne("DivanSufi.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("DivanSufi.Domain.Entities.WaslaItem", b =>
                {
                    b.HasOne("DivanSufi.Domain.Entities.Poem", "Poem")
                        .WithMany("WaslaItems")
                        .HasForeignKey("PoemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DivanSufi.Domain.Entities.Wasla", "Wasla")
                        .WithMany("Items")
                        .HasForeignKey("WaslaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poem");

                    b.Navigation("Wasla");
                });

            modelBuilder.Entity("DivanSufi.Domain.Entities.Maqam", b =>
                {
                    b.Navigation("Poems");
                });

            modelBuilder.Entity("DivanSufi.Domain.Entities.Poem", b =>
                {
                    b.Navigation("WaslaItems");
                });

            modelBuilder.Entity("DivanSufi.Domain.Entities.Poet", b =>
                {
                    b.Navigation("Poems");
                });

            modelBuilder.Entity("DivanSufi.Domain.Entities.Wasla", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
